const jwt = require('jsonwebtoken');

// In-Memory fallback store when MongoDB is not connected
const mockProfile = {
  name: 'Hariharan Ravikumar',
  titles: [
    'Full Stack Software Engineer',
    'MERN Stack Developer',
    'React.js Specialist',
    'Node.js & Express Architect',
    'Technical Support Engineer',
  ],
  shortIntro:
    'Passionate Full Stack Developer specializing in modern JavaScript, MERN stack architectures, and high-performance, accessible digital experiences.',
  about:
    'I am Hariharan Ravikumar, an enthusiastic Full Stack Engineer dedicated to designing and developing robust web systems. With a strong foundation in modern JavaScript, React, Node.js, Express, and MongoDB, I bridge technical excellence with clean, user-centric interface design. Whether crafting responsive single-page applications or designing performant RESTful microservices, I deliver scalable and maintainable solutions.',
  careerObjective:
    'To contribute as an innovative Full Stack / Software Engineer within an agile, forward-thinking team, building impactful applications and driving business value through clean code and modern web architectures.',
  profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
  socialLinks: {
    github: 'https://github.com/hariharan-ravikumar',
    linkedin: 'https://linkedin.com/in/hariharan-ravikumar',
    twitter: 'https://twitter.com/hariharan_dev',
    portfolio: 'https://hariharan.dev',
    email: 'admin@hariharan.dev',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
  },
  stats: {
    yearsExperience: 1,
    completedProjects: 3,
    happyClients: 0,
    codeCommits: 0,
  },
  education: [
    {
      institution: 'Anna University / Regional Campus',
      degree: 'Bachelor of Engineering (B.E.)',
      field: 'Computer Science and Engineering',
      startYear: '2020',
      endYear: '2024',
      grade: '8.6 CGPA',
      description: 'Specialized in Data Structures, Database Systems, and Web Engineering.',
    },
    {
      institution: 'Higher Secondary School',
      degree: 'HSC (+2)',
      field: 'Computer Science & Mathematics',
      startYear: '2018',
      endYear: '2020',
      grade: '92.5%',
      description: 'Completed Higher Secondary with top honors in Computer Science and Mathematics.',
    },
  ],
  achievements: [
    {
      title: 'First Place - National Level Web Hackathon',
      organization: 'TechFest Innovate',
      year: '2023',
      description: 'Built real-time collaborative workspace using React and WebSockets in 36 hours.',
    },
  ],
  strengths: [
    'Problem Solving & Clean Code Architecture',
    'End-to-End Full Stack Web Application Development',
    'Responsive Glassmorphism & Modern UI/UX Implementation',
    'REST API Design & Database Schema Optimization',
    'Cross-browser Compatibility & Performance Auditing',
  ],
  languages: [
    { language: 'English', proficiency: 'Professional Working Proficiency', level: 95 },
    { language: 'Tamil', proficiency: 'Native / Bilingual', level: 100 },
  ],
};

const mockSkills = [
  { _id: 's1', name: 'HTML5', category: 'Frontend', proficiency: 95, order: 1 },
  { _id: 's2', name: 'CSS3 / Glassmorphism', category: 'Frontend', proficiency: 90, order: 2 },
  { _id: 's3', name: 'JavaScript (ES6+)', category: 'Frontend', proficiency: 92, order: 3 },
  { _id: 's4', name: 'React.js', category: 'Frontend', proficiency: 90, order: 4 },
  { _id: 's5', name: 'Redux Toolkit / Context', category: 'Frontend', proficiency: 85, order: 5 },
  { _id: 's6', name: 'Node.js', category: 'Backend', proficiency: 88, order: 6 },
  { _id: 's7', name: 'Express.js', category: 'Backend', proficiency: 90, order: 7 },
  { _id: 's8', name: 'RESTful API Architecture', category: 'Backend', proficiency: 92, order: 8 },
  { _id: 's9', name: 'JWT & Security', category: 'Backend', proficiency: 88, order: 9 },
  { _id: 's10', name: 'MongoDB & Mongoose', category: 'Database', proficiency: 88, order: 10 },
  { _id: 's11', name: 'MySQL', category: 'Database', proficiency: 80, order: 11 },
  { _id: 's12', name: 'Git & GitHub', category: 'Tools', proficiency: 90, order: 12 },
  { _id: 's13', name: 'VS Code & Postman', category: 'Tools', proficiency: 95, order: 13 },
  { _id: 's14', name: 'Vercel & Railway Deployment', category: 'Tools', proficiency: 85, order: 14 },
];

const mockProjects = [
  {
    _id: 'p1',
    title: 'DevPulse - Full Stack Developer Career & Resume Platform',
    slug: 'devpulse-developer-career-platform',
    shortDescription: 'Comprehensive resume management and developer portfolio engine with JWT authentication, visitor analytics, and automated contact notifications.',
    fullDescription: 'Engineered a production-ready portfolio and resume dispatch platform featuring role-based access control, multiple downloadable categorized resumes, visitor telemetry, and multi-channel notifications.',
    category: 'MERN Stack',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB Atlas', 'JWT', 'Nodemailer', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    ],
    githubLink: 'https://github.com/hariharan-ravikumar/devpulse-portfolio',
    liveDemo: 'https://hariharan.dev',
    pdfUrl: '/resumes/sample_resume.pdf',
    featured: true,
  },
  {
    _id: 'p2',
    title: 'ShopZen - Modern MERN E-Commerce Ecosystem',
    slug: 'shopzen-modern-mern-ecommerce',
    shortDescription: 'Full featured e-commerce application with product filtering, cart state management, checkout, and administrative catalog controls.',
    fullDescription: 'Built with React, Redux, Express, and MongoDB. Features secure token authentication, product reviews, and comprehensive analytics for sales and inventory tracking.',
    category: 'Full Stack',
    technologies: ['React', 'Redux Toolkit', 'Express.js', 'MongoDB', 'Cloudinary', 'JWT'],
    image: 'https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&w=800&q=80',
    screenshots: ['https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&w=800&q=80'],
    githubLink: 'https://github.com/hariharan-ravikumar/shopzen-ecommerce',
    liveDemo: 'https://github.com/hariharan-ravikumar/shopzen-ecommerce#readme',
    pdfUrl: '',
    featured: true,
  },
  {
    _id: 'p3',
    title: 'TaskFlow - Collaborative Agile Project Management Tool',
    slug: 'taskflow-agile-project-tool',
    shortDescription: 'Kanban-style team productivity application with drag-and-drop task tracking, column workflows, and priority management.',
    fullDescription: 'Responsive single-page application crafted with React and CSS animations, backed by Express REST APIs with granular project permission controls.',
    category: 'Frontend',
    technologies: ['React', 'CSS3', 'Axios', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?auto=format&fit=crop&w=800&q=80',
    screenshots: ['https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?auto=format&fit=crop&w=800&q=80'],
    githubLink: 'https://github.com/hariharan-ravikumar/taskflow-app',
    liveDemo: 'https://github.com/hariharan-ravikumar/taskflow-app#readme',
    pdfUrl: '',
    featured: true,
  },
];

const mockExperiences = [
  {
    _id: 'e1',
    company: 'TechNovus Solutions Pvt Ltd',
    role: 'Full Stack Developer Intern',
    type: 'Internship',
    location: 'Chennai, Tamil Nadu (Hybrid)',
    startDate: 'January 2024',
    endDate: 'June 2024',
    isCurrent: false,
    responsibilities: [
      'Developed interactive React frontend modules and integrated reusable glassmorphic UI components.',
      'Engineered scalable Node.js/Express REST APIs for user profile and document workflows.',
      'Optimized MongoDB aggregate queries, reducing endpoint latency by 28%.',
      'Participated in daily agile stand-ups, code reviews, and Git feature-branch workflows.',
    ],
    technologies: ['React', 'Node.js', 'Express.js', 'MongoDB', 'Git', 'Postman'],
    certificateUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    _id: 'e2',
    company: 'InnovateX Labs',
    role: 'Web Development & Technical Support Intern',
    type: 'Internship',
    location: 'Remote',
    startDate: 'July 2023',
    endDate: 'December 2023',
    isCurrent: false,
    responsibilities: [
      'Assisted in maintaining client web portals, resolving UI defects, and diagnosing network/API issues.',
      'Implemented responsive CSS layouts ensuring 100% mobile and tablet browser compatibility.',
      'Drafted technical support documentation and API integration guides for client onboarding.',
    ],
    technologies: ['JavaScript', 'HTML5', 'CSS3', 'REST APIs', 'Technical Support'],
    certificateUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
];

const mockCertificates = [
  {
    _id: 'c1',
    title: 'Full Stack Web Development (MERN)',
    issuer: 'Coursera / Meta',
    issueDate: 'May 2024',
    credentialId: 'META-MERN-892401',
    credentialUrl: 'https://coursera.org',
    imagePreview: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?auto=format&fit=crop&w=800&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tags: ['React', 'Node.js', 'Express', 'MongoDB'],
  },
  {
    _id: 'c2',
    title: 'JavaScript Algorithms and Data Structures',
    issuer: 'freeCodeCamp',
    issueDate: 'November 2023',
    credentialId: 'FCC-JS-77491',
    credentialUrl: 'https://freecodecamp.org',
    imagePreview: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=800&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tags: ['JavaScript', 'Algorithms'],
  },
  {
    _id: 'c3',
    title: 'Responsive Web Design Certification',
    issuer: 'freeCodeCamp',
    issueDate: 'August 2023',
    credentialId: 'FCC-RWD-12048',
    credentialUrl: 'https://freecodecamp.org',
    imagePreview: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=800&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tags: ['HTML5', 'CSS3'],
  },
];

const dummyPdfUrl = '/resumes/sample_resume.pdf';
let mockResumes = [
  {
    _id: 'r1',
    title: 'Full Stack Developer Resume',
    category: 'Full Stack Developer Resume',
    description: 'Comprehensive resume highlighting full-lifecycle web development, end-to-end architectures, React frontends, Node/Express backends, and database administration.',
    fileUrl: dummyPdfUrl,
    fileName: 'Hariharan_Ravikumar_Full_Stack_Developer_Resume.pdf',
    fileSize: '194 KB',
    downloadCount: 142,
    isActive: true,
    isDefault: true,
    version: 'v2.4',
    lastUpdated: new Date(),
  },
  {
    _id: 'r2',
    title: 'MERN Stack Developer Resume',
    category: 'MERN Stack Developer Resume',
    description: 'Tailored specifically for MERN stack roles, focusing on MongoDB schema design, Express REST microservices, React state machines, and Node server optimizations.',
    fileUrl: dummyPdfUrl,
    fileName: 'Hariharan_Ravikumar_MERN_Stack_Resume.pdf',
    fileSize: '188 KB',
    downloadCount: 98,
    isActive: true,
    isDefault: false,
    version: 'v2.3',
    lastUpdated: new Date(),
  },
  {
    _id: 'r3',
    title: 'Frontend Developer Resume',
    category: 'Frontend Developer Resume',
    description: 'Focused on modern client-side engineering: React.js, JavaScript (ES6+), responsive CSS architectures, accessibility, and modern UI/UX design patterns.',
    fileUrl: dummyPdfUrl,
    fileName: 'Hariharan_Ravikumar_Frontend_Developer_Resume.pdf',
    fileSize: '180 KB',
    downloadCount: 84,
    isActive: true,
    isDefault: false,
    version: 'v2.1',
    lastUpdated: new Date(),
  },
  {
    _id: 'r4',
    title: 'Software Engineer Resume',
    category: 'Software Engineer Resume',
    description: 'Emphasizes Core Computer Science principles, Data Structures & Algorithms, Object-Oriented Analysis, testing paradigms, and system design fundamentals.',
    fileUrl: dummyPdfUrl,
    fileName: 'Hariharan_Ravikumar_Software_Engineer_Resume.pdf',
    fileSize: '185 KB',
    downloadCount: 65,
    isActive: true,
    isDefault: false,
    version: 'v2.0',
    lastUpdated: new Date(),
  },
  {
    _id: 'r5',
    title: 'Technical Support Engineer Resume',
    category: 'Technical Support Engineer Resume',
    description: 'Geared toward Technical Support, systems troubleshooting, API diagnostics, customer-facing technical issue resolution, and infrastructure debugging.',
    fileUrl: dummyPdfUrl,
    fileName: 'Hariharan_Ravikumar_Technical_Support_Resume.pdf',
    fileSize: '175 KB',
    downloadCount: 41,
    isActive: true,
    isDefault: false,
    version: 'v1.8',
    lastUpdated: new Date(),
  },
];

let mockMessages = [
  {
    _id: 'm1',
    name: 'Priya Sharma',
    email: 'priya.sharma@techventures.in',
    phone: '+91 94433 22110',
    company: 'TechVentures India',
    subject: 'Full Stack Developer Opportunity',
    message: 'Hello Hariharan, we reviewed your projects and would love to discuss a Full Stack Engineer role at TechVentures.',
    isRead: false,
    status: 'new',
    createdAt: new Date(),
  },
];

module.exports = {
  mockProfile,
  mockSkills,
  mockProjects,
  mockExperiences,
  mockCertificates,
  mockResumes,
  mockMessages,
};
